/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.FornecedorDAO;
import MODEL.Fornecedor;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUSTAVO
 */
public class ConcultarFornecedorJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConcultarFornecedorJFrame
     */
    public ConcultarFornecedorJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FornecedorjTable = new javax.swing.JTable();
        concultarfornecedor_codigojText = new javax.swing.JTextField();
        concultarfornecedor_nomefantasiajText = new javax.swing.JTextField();
        concultarfornecedor_cnpjjText = new javax.swing.JTextField();
        concultarfornecedor_inscestadualjText = new javax.swing.JTextField();
        concultarfornecedor_inscmunipaljText = new javax.swing.JTextField();
        castrarfornecedor = new javax.swing.JButton();
        CODIGO = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FornecedorjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME FANTASIA", "RAZAO SOCIAL", "CNPJ", "INCRIÇÃO ESTADUAL", "INCRIÇÃO MUNICIPAL", "ENDEREÇO", "TELEFONE", "CELULAR", "DATA DE ABERTURA", "E-MAIL", "OBSERVAÇÃO"
            }
        ));
        jScrollPane1.setViewportView(FornecedorjTable);

        concultarfornecedor_nomefantasiajText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concultarfornecedor_nomefantasiajTextActionPerformed(evt);
            }
        });

        castrarfornecedor.setText("CADASTRAR FORNECEDOR");
        castrarfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castrarfornecedorActionPerformed(evt);
            }
        });

        CODIGO.setText("CODIGO");
        CODIGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODIGOActionPerformed(evt);
            }
        });

        jRadioButton1.setText("NOME FANTASIA");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("CNPJ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("INSC ESTADUAL");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("INSC MUNICIPAL");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(castrarfornecedor))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(concultarfornecedor_codigojText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CODIGO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(concultarfornecedor_nomefantasiajText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(concultarfornecedor_cnpjjText, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(concultarfornecedor_inscestadualjText, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(concultarfornecedor_inscmunipaljText, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton4))
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(castrarfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CODIGO)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concultarfornecedor_codigojText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concultarfornecedor_nomefantasiajText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concultarfornecedor_cnpjjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concultarfornecedor_inscestadualjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concultarfornecedor_inscmunipaljText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concultarfornecedor_nomefantasiajTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concultarfornecedor_nomefantasiajTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concultarfornecedor_nomefantasiajTextActionPerformed

    private void castrarfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castrarfornecedorActionPerformed
      
        Cadastro_FornecedorJFrame frame = new Cadastro_FornecedorJFrame();

        frame.setVisible(true);
        
    }//GEN-LAST:event_castrarfornecedorActionPerformed

    private void CODIGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODIGOActionPerformed
        
        listarFornecedorcod(Integer.parseInt(concultarfornecedor_codigojText.getText()));
        
    }//GEN-LAST:event_CODIGOActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        
        listarFornecedorNomefantasia(concultarfornecedor_nomefantasiajText.getText());
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       
        listarFornecedorCNPJ(concultarfornecedor_cnpjjText.getText());
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        
        listarFornecedorInscricaoestadual(concultarfornecedor_inscestadualjText.getText());
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        
        listarFornecedorInscricaomunicipal(concultarfornecedor_inscmunipaljText.getText());
        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    public void listarFornecedorcod(int cod)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) FornecedorjTable.getModel();
      val.getDataVector().removeAllElements();
      FornecedorDAO foDAO = new FornecedorDAO();
      List<Fornecedor> fornecedor = foDAO.listarFornecedorcod(cod);
      int i=0;
      while(fornecedor.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(fornecedor.get(i).getCodigo()), fornecedor.get(i).getNomefantasia(), fornecedor.get(i).getRazaosocial(), fornecedor.get(i).getCnpj(),
               fornecedor.get(i).getInscricaoestadual(), fornecedor.get(i).getInscricaomunicipal(), fornecedor.get(i).getEndereco(), fornecedor.get(i).getTelefonecomercial(), fornecedor.get(i).getCelular(), fornecedor.get(i).getDataaberturaempresa(), fornecedor.get(i).getEmail(),fornecedor.get(i).getObservacao()});
           i++;
          }
         
  
    }
    
    
    
    public void listarFornecedorNomefantasia(String nomefantasia)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) FornecedorjTable.getModel();
      val.getDataVector().removeAllElements();
      FornecedorDAO foDAO = new FornecedorDAO();
      List<Fornecedor> fornecedor = foDAO.listarFornecedorNomefantasia(nomefantasia);
      int i=0;
      while(fornecedor.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(fornecedor.get(i).getCodigo()), fornecedor.get(i).getNomefantasia(), fornecedor.get(i).getRazaosocial(), fornecedor.get(i).getCnpj(),
               fornecedor.get(i).getInscricaoestadual(), fornecedor.get(i).getInscricaomunicipal(), fornecedor.get(i).getEndereco(), fornecedor.get(i).getTelefonecomercial(), fornecedor.get(i).getCelular(), fornecedor.get(i).getDataaberturaempresa(), fornecedor.get(i).getEmail(),fornecedor.get(i).getObservacao()});
           i++;
          }
         
  
    }
    
    public void listarFornecedorCNPJ(String CNPJ)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) FornecedorjTable.getModel();
      val.getDataVector().removeAllElements();
      FornecedorDAO foDAO = new FornecedorDAO();
      List<Fornecedor> fornecedor = foDAO.listarFornecedorCNPJ(CNPJ);
      int i=0;
      while(fornecedor.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(fornecedor.get(i).getCodigo()), fornecedor.get(i).getNomefantasia(), fornecedor.get(i).getRazaosocial(), fornecedor.get(i).getCnpj(),
               fornecedor.get(i).getInscricaoestadual(), fornecedor.get(i).getInscricaomunicipal(), fornecedor.get(i).getEndereco(), fornecedor.get(i).getTelefonecomercial(), fornecedor.get(i).getCelular(), fornecedor.get(i).getDataaberturaempresa(), fornecedor.get(i).getEmail(),fornecedor.get(i).getObservacao()});
           i++;
          }
         
  
    }
    
    public void listarFornecedorInscricaoestadual(String inscricaoestadual)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) FornecedorjTable.getModel();
      val.getDataVector().removeAllElements();
      FornecedorDAO foDAO = new FornecedorDAO();
      List<Fornecedor> fornecedor = foDAO.listarFornecedorInscricaoestadual(inscricaoestadual);
      int i=0;
      while(fornecedor.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(fornecedor.get(i).getCodigo()), fornecedor.get(i).getNomefantasia(), fornecedor.get(i).getRazaosocial(), fornecedor.get(i).getCnpj(),
               fornecedor.get(i).getInscricaoestadual(), fornecedor.get(i).getInscricaomunicipal(), fornecedor.get(i).getEndereco(), fornecedor.get(i).getTelefonecomercial(), fornecedor.get(i).getCelular(), fornecedor.get(i).getDataaberturaempresa(), fornecedor.get(i).getEmail(),fornecedor.get(i).getObservacao()});
           i++;
          }
         
  
    }
    
    public void listarFornecedorInscricaomunicipal(String inscricaomunicipal)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) FornecedorjTable.getModel();
      val.getDataVector().removeAllElements();
      FornecedorDAO foDAO = new FornecedorDAO();
      List<Fornecedor> fornecedor = foDAO.listarFornecedorInscricaomunicipal(inscricaomunicipal);
      int i=0;
      while(fornecedor.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(fornecedor.get(i).getCodigo()), fornecedor.get(i).getNomefantasia(), fornecedor.get(i).getRazaosocial(), fornecedor.get(i).getCnpj(),
               fornecedor.get(i).getInscricaoestadual(), fornecedor.get(i).getInscricaomunicipal(), fornecedor.get(i).getEndereco(), fornecedor.get(i).getTelefonecomercial(), fornecedor.get(i).getCelular(), fornecedor.get(i).getDataaberturaempresa(), fornecedor.get(i).getEmail(),fornecedor.get(i).getObservacao()});
           i++;
          }
         
  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcultarFornecedorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcultarFornecedorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcultarFornecedorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcultarFornecedorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcultarFornecedorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CODIGO;
    private javax.swing.JTable FornecedorjTable;
    private javax.swing.JButton castrarfornecedor;
    private javax.swing.JTextField concultarfornecedor_cnpjjText;
    private javax.swing.JTextField concultarfornecedor_codigojText;
    private javax.swing.JTextField concultarfornecedor_inscestadualjText;
    private javax.swing.JTextField concultarfornecedor_inscmunipaljText;
    private javax.swing.JTextField concultarfornecedor_nomefantasiajText;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
