 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.ClienteDAO;
import MODEL.Cliente;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUSTAVO
 */
public class ConcultarClienteJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConcultarClienteJFrame
     */
    public ConcultarClienteJFrame() {
        initComponents();
        ListarTabelaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientejTable = new javax.swing.JTable();
        conculta_cliente_codigojText = new javax.swing.JTextField();
        conculta_cliente_cpfjText = new javax.swing.JTextField();
        conculta_cliente_cnpjText = new javax.swing.JTextField();
        conculta_cliente_DatanascjText = new javax.swing.JTextField();
        conculta_cliente_nomejText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clientejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME", "CPF", "CNPJ", "DATA NASC", "ENDERECO", "TELEFONE", "CELULAR", "ENDERECO ENTREGA", "E-MAIL", "OBSERVAÇÃO"
            }
        ));
        clientejTable.setSelectionBackground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setViewportView(clientejTable);

        conculta_cliente_codigojText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conculta_cliente_codigojTextActionPerformed(evt);
            }
        });

        conculta_cliente_cpfjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conculta_cliente_cpfjTextActionPerformed(evt);
            }
        });

        jButton1.setText("CADASTRAR NOVO CLIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("CODIGO");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("PESQUISAR NOME");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("PESQUISAR CPF");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("PESQUISAR CNPJ");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("PESQUISAR DATA NASC");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conculta_cliente_codigojText, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(conculta_cliente_nomejText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(29, 29, 29)
                                .addComponent(jRadioButton2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conculta_cliente_cpfjText, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(conculta_cliente_cnpjText, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(conculta_cliente_DatanascjText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conculta_cliente_codigojText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conculta_cliente_nomejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conculta_cliente_cpfjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conculta_cliente_cnpjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conculta_cliente_DatanascjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ClientesJFrame frame = new ClientesJFrame();

        frame.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        
        ListarTabelaClientecodigo(Integer.parseInt(conculta_cliente_codigojText.getText()));
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        
        ListarTabelaClientenome(conculta_cliente_nomejText.getText());
        
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        
        ListarTabelaClientecpf(conculta_cliente_cpfjText.getText());
        
        
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
       
        ListarTabelaClientecnpj(conculta_cliente_cnpjText.getText());
        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
       
        ListarTabelaClientedatanasc(conculta_cliente_DatanascjText.getText());
        
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void conculta_cliente_cpfjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conculta_cliente_cpfjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conculta_cliente_cpfjTextActionPerformed

    private void conculta_cliente_codigojTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conculta_cliente_codigojTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conculta_cliente_codigojTextActionPerformed

    public void ListarTabelaCliente()
    {
        
        
      DefaultTableModel val = (DefaultTableModel) clientejTable.getModel();
      val.getDataVector().removeAllElements();
      ClienteDAO cliDAO = new ClienteDAO();
      List<Cliente> cliente = cliDAO.listarClientes();
      int i=0;
      while(cliente.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(cliente.get(i).getCodigo()), cliente.get(i).getNome(), cliente.get(i).getCpf(), cliente.get(i).getCnpj(), cliente.get(i).getDatanasc(), cliente.get(i).getEndereco(), cliente.get(i).getTelefone(), cliente.get(i).getCelular(), cliente.get(i).getEnderecoentrega(), cliente.get(i).getEmail(), cliente.get(i).getObservacao()});
           i++;
          }
         
  
    }
    
    public void ListarTabelaClientecodigo(int cod)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) clientejTable.getModel();
      val.getDataVector().removeAllElements();
      ClienteDAO cliDAO = new ClienteDAO();
      List<Cliente> cliente = cliDAO.listarClientespesquisacod(cod);
      int i=0;
      while(cliente.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(cliente.get(i).getCodigo()), cliente.get(i).getNome(), cliente.get(i).getCpf(), cliente.get(i).getCnpj(), cliente.get(i).getDatanasc(), cliente.get(i).getEndereco(), cliente.get(i).getTelefone(), cliente.get(i).getCelular(), cliente.get(i).getEnderecoentrega(), cliente.get(i).getEmail(), cliente.get(i).getObservacao()});
           i++;
          }
    }
      public void ListarTabelaClientenome(String nome)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) clientejTable.getModel();
      val.getDataVector().removeAllElements();
      ClienteDAO cliDAO = new ClienteDAO();
      List<Cliente> cliente = cliDAO.listarClientespesquisanome(nome);
      int i=0;
      while(cliente.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(cliente.get(i).getCodigo()), cliente.get(i).getNome(), cliente.get(i).getCpf(), cliente.get(i).getCnpj(), cliente.get(i).getDatanasc(), cliente.get(i).getEndereco(), cliente.get(i).getTelefone(), cliente.get(i).getCelular(), cliente.get(i).getEnderecoentrega(), cliente.get(i).getEmail(), cliente.get(i).getObservacao()});
           i++;
          }
         
  
    }
    
      public void ListarTabelaClientecpf(String cpf)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) clientejTable.getModel();
      val.getDataVector().removeAllElements();
      ClienteDAO cliDAO = new ClienteDAO();
      List<Cliente> cliente = cliDAO.listarClientespesquisacpf(cpf);
      int i=0;
      while(cliente.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(cliente.get(i).getCodigo()), cliente.get(i).getNome(), cliente.get(i).getCpf(), cliente.get(i).getCnpj(), cliente.get(i).getDatanasc(), cliente.get(i).getEndereco(), cliente.get(i).getTelefone(), cliente.get(i).getCelular(), cliente.get(i).getEnderecoentrega(), cliente.get(i).getEmail(), cliente.get(i).getObservacao()});
           i++;
          }
         
  
    }
      
      
      public void ListarTabelaClientecnpj(String cnpj)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) clientejTable.getModel();
      val.getDataVector().removeAllElements();
      ClienteDAO cliDAO = new ClienteDAO();
      List<Cliente> cliente = cliDAO.listarClientespesquisacnpj(cnpj);
      int i=0;
      while(cliente.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(cliente.get(i).getCodigo()), cliente.get(i).getNome(), cliente.get(i).getCpf(), cliente.get(i).getCnpj(), cliente.get(i).getDatanasc(), cliente.get(i).getEndereco(), cliente.get(i).getTelefone(), cliente.get(i).getCelular(), cliente.get(i).getEnderecoentrega(), cliente.get(i).getEmail(), cliente.get(i).getObservacao()});
           i++;
          }
         
  
    }
      
      public void ListarTabelaClientedatanasc(String datanasc)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) clientejTable.getModel();
      val.getDataVector().removeAllElements();
      ClienteDAO cliDAO = new ClienteDAO();
      List<Cliente> cliente = cliDAO.listarClientespesquisadatanasc(datanasc);
      int i=0;
      while(cliente.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(cliente.get(i).getCodigo()), cliente.get(i).getNome(), cliente.get(i).getCpf(), cliente.get(i).getCnpj(), cliente.get(i).getDatanasc(), cliente.get(i).getEndereco(), cliente.get(i).getTelefone(), cliente.get(i).getCelular(), cliente.get(i).getEnderecoentrega(), cliente.get(i).getEmail(), cliente.get(i).getObservacao()});
           i++;
          }
         
  
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConcultarClienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConcultarClienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConcultarClienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConcultarClienteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConcultarClienteJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientejTable;
    private javax.swing.JTextField conculta_cliente_DatanascjText;
    private javax.swing.JTextField conculta_cliente_cnpjText;
    private javax.swing.JTextField conculta_cliente_codigojText;
    private javax.swing.JTextField conculta_cliente_cpfjText;
    private javax.swing.JTextField conculta_cliente_nomejText;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
