/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;


import DAO.Dao;
import DAO.ItensVendasDAO;
import DAO.ProdutosDAO;
import DAO.VendaDAO;
import MODEL.ItensVendas;
import MODEL.Produto;
import MODEL.Vendas;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUSTAVO
 */
public class VendasJFrame extends javax.swing.JFrame {

    public Connection conecta;

    /**
     * Creates new form VendasJFrame
     */
    public VendasJFrame() {
        initComponents();
        this.conecta = new Dao().conecta();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextCodProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextQtd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LancarVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaVendas = new javax.swing.JTable();
        ValortotaljText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CpfVendajText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("CODIGO DO PRODUTO");

        jLabel3.setText("QUANTIDADE");

        LancarVenda.setText("LANÇAR VENDA");
        LancarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LancarVendaActionPerformed(evt);
            }
        });

        TabelaVendas.setAutoCreateRowSorter(true);
        TabelaVendas.setBackground(new java.awt.Color(255, 255, 0));
        TabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO PRODUTO", "QTD", "PRODUTO", "VALOR"
            }
        ));
        TabelaVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaVendasMouseClicked(evt);
            }
        });
        TabelaVendas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                TabelaVendasComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaVendas);
        if (TabelaVendas.getColumnModel().getColumnCount() > 0) {
            TabelaVendas.getColumnModel().getColumn(1).setMaxWidth(50);
        }

        jLabel4.setText("VALOR TOTAL");

        jLabel5.setText("CPF DO CLIENTE QUE IRA PAGAR");

        jButton1.setText("FINALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CpfVendajText, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ValortotaljText, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LancarVenda))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(191, 191, 191)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(305, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LancarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValortotaljText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CpfVendajText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LancarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LancarVendaActionPerformed
     
     int linhas = TabelaVendas.getRowCount(); //numero de linhas da tabela  
        int coluna = 0; //numero da coluna que vc quer verificar  
        boolean tem = false; //se false, quer dizer que não tem o item  
        String valor = jTextCodProduto.getText(); //objeto que você quer verificar  
          
        for(int i = 0; i<linhas;i++){  
            String item = (String) TabelaVendas.getValueAt(i, coluna);  
               if(item.equals(valor)) tem = true;  
        }  
          
        if(tem) {  
            listarItensVendas(jTextCodProduto.getText());
            
            
            
                 ItensVendas iten = new ItensVendas();
                 iten.setItensvendacodigoproduto(jTextCodProduto.getText());
     
                 iten.setItensquantidade(Integer.parseInt(jTextQtd.getText()));

     
                 ItensVendasDAO ItenDAO = new ItensVendasDAO();
                 ItenDAO.ATUALIZARQUANTIDADE(iten);
                 
                     double z =0;
                     for(int y=0; y < TabelaVendas.getRowCount();y++){
                         z+=Double.parseDouble(TabelaVendas.getValueAt(y,3).toString());   
                           }
                               ValortotaljText.setText(z+""); 
                 
                 
                 
        }          
        else{  
               Vendas ven = new Vendas();
    
    ven.setVendacodigoproduto(jTextCodProduto.getText());
    ven.setQuantidade(Integer.parseInt(jTextQtd.getText()));    
    ven.setClientecpf(CpfVendajText.getText());   
    
    
    VendaDAO venDAO = new VendaDAO();
    venDAO.lancarvenda(ven);
    
    
    
    ItensVendas itensven = new ItensVendas();
    
    itensven.setItensvendacodigoproduto(jTextCodProduto.getText());
    itensven.setItensquantidade(Integer.parseInt(jTextQtd.getText()));   
    
    
    ItensVendasDAO itensDAO = new ItensVendasDAO();
    itensDAO.itensvenda(itensven);
    
    
    
    
    listarItensVendas(jTextCodProduto.getText());
      
     
    
    
     Produto pro = new Produto();
     pro.setCodigoproduto(jTextCodProduto.getText());
     
     pro.setQuantidadeproduto(Integer.parseInt(jTextQtd.getText()));

     
     ProdutosDAO proDAO = new ProdutosDAO();
     proDAO.ATUALIZARESTOQUE(pro);
    
    
    double z =0;
    for(int y=0; y < TabelaVendas.getRowCount();y++){
        z+=Double.parseDouble(TabelaVendas.getValueAt(y,3).toString());   
    }
    ValortotaljText.setText(z+"");  
    
    
    
    
        }     
        
        
        
        
        
        
        
        
        

    
    }//GEN-LAST:event_LancarVendaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
        
        
    ItensVendasDAO itensDAO = new ItensVendasDAO();
    itensDAO.deletar();
        JOptionPane.showMessageDialog(this, "VENDA FINALIZADA");
        
        
        
        CadastrarContasReceberJFrame frame = new CadastrarContasReceberJFrame();

        frame.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TabelaVendasComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TabelaVendasComponentHidden

    }//GEN-LAST:event_TabelaVendasComponentHidden

    private void TabelaVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaVendasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaVendasMouseClicked
 

            
    public void listarItensVendas(String ItensVendas)
    {
        
        
      DefaultTableModel val = (DefaultTableModel) TabelaVendas.getModel();
      val.getDataVector();
      ItensVendasDAO ItensDAO = new ItensVendasDAO();
      List<ItensVendas> itensVendas = ItensDAO.listarItensVendas(ItensVendas);
      int i=0;
      while(itensVendas.size() > i)
          {
           val.addRow(new Object[] {String.valueOf(itensVendas.get(i).getItensvendacodigoproduto()), itensVendas.get(i).getItensquantidade(),itensVendas.get(i).getNomeproduto(),itensVendas.get(i).getValorunitario()});
           i++;
          }
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CpfVendajText;
    private javax.swing.JButton LancarVenda;
    private javax.swing.JTable TabelaVendas;
    private javax.swing.JTextField ValortotaljText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCodProduto;
    private javax.swing.JTextField jTextQtd;
    // End of variables declaration//GEN-END:variables
}
